/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : System Colors
 #	author : miyako
 #	2018/11/01
 #
 # --------------------------------------------------------------------------------*/


#include "libjson_methods.h"
#include <mutex>

// --- Get System Color
void Get_system_colors(sLONG_PTR *pResult, PackagePtr pParams);
