/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-System-Colors.h
 #	source generated by 4D Plugin Wizard
 #	Project : System Colors
 #	author : miyako
 #	2021/04/04
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_SYSTEM_COLORS_H
#define PLUGIN_SYSTEM_COLORS_H

#include "4DPluginAPI.h"
#include "4DPlugin-JSON.h"

#import <Cocoa/Cocoa.h>

#pragma mark -

void Get_system_colors(PA_PluginParameters params);

#endif /* PLUGIN_SYSTEM_COLORS_H */
